Meteor.subscribe('Noticias');
Meteor.subscribe('Atividades');
Meteor.subscribe("Credenciamentos");
Meteor.subscribe('Achievements');
Meteor.subscribe("allUserData");
Meteor.subscribe("UserData");
Meteor.subscribe("Patrocinadores");
Meteor.subscribe("Perguntas");
moment.lang('pt');
